# node

今天踩了个大坑, 记录一下. try {} catch(err){} 是确实不能捕获异步错误的, 同步错误是可以捕捉得到.但是虽然这么说, 很多人还是会在编码的时候犯错误, 就是
```
try {

  do(function(){
    setTimeout(() => {
      throw err;
    });
  });
} catch(err) {
  console.log(err);
}
```
所以一不做二不休, 在设计 api 的时候, 就要贯彻到底 err first 的宗旨, 这里小小吐槽一下 nos, 一开始就是回调处理函数, 但是在函数内部很深层级 throw 一个错误是不好的设计.
所以这里就能体会到 yield + co 的好处了.
在设计的时候, 尽量是 callback(new Error()).
分清楚什么是操作失败与程序 bug.操作失败是指一个网络请求错误, 网络请求被挂起, 无效的输入, 链接不到服务器, 这样的, 而 bug 是该传对象却传了一个字符串, 读取一个 undefined 的
属性.举个例子就是, 程序需要链接服务器, 但是服务器宕机了, 然后返回一个 ECONNECTIONREFUSE 错误, 这个是操作错误, 但是程序没有监听 error 事件导致程序崩溃这个就是编码代码的失误,
这个就是一个 bug.